// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiW--8gW1wbusBoqQnn3ngkj16KuqqoG0',
    appId: '1:183542711477:web:f128a2cf731ac297b46afc',
    messagingSenderId: '183542711477',
    projectId: 'khaddemni-f03d0',
    authDomain: 'khaddemni-f03d0.firebaseapp.com',
    storageBucket: 'khaddemni-f03d0.firebasestorage.app',
    measurementId: 'G-8W227EJ0B4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCN7sAnKEDkyxBQKGgCPhQVgqQH22UDcb8',
    appId: '1:183542711477:android:3ae9e71c65e18048b46afc',
    messagingSenderId: '183542711477',
    projectId: 'khaddemni-f03d0',
    storageBucket: 'khaddemni-f03d0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPzoKR3MrhcpvmtAQvkVqH_6HpUtE3v4g',
    appId: '1:183542711477:ios:59840fdb1c753284b46afc',
    messagingSenderId: '183542711477',
    projectId: 'khaddemni-f03d0',
    storageBucket: 'khaddemni-f03d0.firebasestorage.app',
    iosBundleId: 'com.example.khaddemniApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPzoKR3MrhcpvmtAQvkVqH_6HpUtE3v4g',
    appId: '1:183542711477:ios:59840fdb1c753284b46afc',
    messagingSenderId: '183542711477',
    projectId: 'khaddemni-f03d0',
    storageBucket: 'khaddemni-f03d0.firebasestorage.app',
    iosBundleId: 'com.example.khaddemniApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAiW--8gW1wbusBoqQnn3ngkj16KuqqoG0',
    appId: '1:183542711477:web:d2e63c209b277591b46afc',
    messagingSenderId: '183542711477',
    projectId: 'khaddemni-f03d0',
    authDomain: 'khaddemni-f03d0.firebaseapp.com',
    storageBucket: 'khaddemni-f03d0.firebasestorage.app',
    measurementId: 'G-E35QWDK64J',
  );
}
